spring:
    application:
        name: hotel
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://roundhouse.proxy.rlwy.net:20445/railway
        username: root
        password: E5eDDbEAEdfHhCa1E4hbhhbFGFGEB1Db

jpa:
    hibernate:
        ddl-auto: update
    show-sql: true
    properties:
        hibernate:
            dialect: org.hibernate.dialect.MySQL8Dialect

javax.persistence.jdbc.url: jdbc:mysql://roundhouse.proxy.rlwy.net:20445/railway

